owner: cjgvrp
repo: cjgvrp-status-page

sites:
  - name: CJGVRP Identify Site 
    url: https://id-dev.cjgvrp.com/s/status # TODO: Update URL

status-website:
  cname: status.cjgvrp.com
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: CJGVRP Status Page
  introTitle: "Welcome to the official CJGVRP Status page"
  introMessage: This is a status page which uses **real-time** data. If a service goes down, the development department is automatically notified so no need to tell us
  theme: ocean
  navbar:
    - title: Status
      href: /

# See https://upptime.js.org/docs/configuration
